export const patientsDatabase: Record<number, any> = {
  1: {
    name: "Kalyan Rao",
    id: "MT8620",
    age: 32,
    dob: "03/28/1985",
    gender: "Male",
    bloodGroup: "AB +ve",
    email: "kalyan.rao@gmail.com",
    phone: "+1 (969)-258-5147",
    address: "286, El Camino Real, California, Zip code: 86251",
    location: "K.K..nagar, Chennai",
    appointmentType: "Offline Appointment",
    diagnosed: ["Diabetes", "BP"],
    initials: "KR",
  },
  2: {
    name: "Radhika Iyer",
    id: "MT8621",
    age: 28,
    dob: "05/15/1987",
    gender: "Female",
    bloodGroup: "O +ve",
    email: "radhika.iyer@gmail.com",
    phone: "+1 (555)-123-4567",
    address: "Plot 45, MG Road, Bangalore, Zip code: 560001",
    location: "K.K..nagar, Chennai",
    appointmentType: "Offline Appointment",
    diagnosed: ["Hypertension"],
    initials: "RI",
  },
  3: {
    name: "Radhika Iyer",
    id: "MT8622",
    age: 45,
    dob: "07/22/1980",
    gender: "Male",
    bloodGroup: "B +ve",
    email: "radhir@gmail.com",
    phone: "+1 (555)-234-5678",
    address: "123 Park Avenue, New Jersey, Zip code: 07003",
    location: "K.K..nagar, Chennai",
    appointmentType: "Offline Appointment",
    diagnosed: ["Thyroid"],
    initials: "RR",
  },
  4: {
    name: "Radhika Iyer",
    id: "MT8623",
    age: 35,
    dob: "11/10/1989",
    gender: "Female",
    bloodGroup: "AB -ve",
    email: "radhika.new@gmail.com",
    phone: "+1 (555)-345-6789",
    address: "456 Elm Street, Texas, Zip code: 75001",
    location: "K.K..nagar, Chennai",
    appointmentType: "Offline Appointment",
    diagnosed: ["Asthma"],
    initials: "RI",
  },
  5: {
    name: "Radhika Iyer",
    id: "MT8624",
    age: 52,
    dob: "02/08/1972",
    gender: "Male",
    bloodGroup: "O -ve",
    email: "radhika.five@gmail.com",
    phone: "+1 (555)-456-7890",
    address: "789 Oak Lane, Florida, Zip code: 33101",
    location: "K.K..nagar, Chennai",
    appointmentType: "Offline Appointment",
    diagnosed: ["Diabetes", "Heart Disease"],
    initials: "RI",
  },
  6: {
    name: "Radhika Iyer",
    id: "MT8625",
    age: 41,
    dob: "09/03/1983",
    gender: "Female",
    bloodGroup: "A +ve",
    email: "radhika.six@gmail.com",
    phone: "+1 (555)-567-8901",
    address: "321 Pine Road, Arizona, Zip code: 85001",
    location: "K.K..nagar, Chennai",
    appointmentType: "Offline Appointment",
    diagnosed: ["Migraine"],
    initials: "RI",
  },
  7: {
    name: "Radhika Iyer",
    id: "MT8626",
    age: 38,
    dob: "06/19/1988",
    gender: "Male",
    bloodGroup: "B -ve",
    email: "radhika.seven@gmail.com",
    phone: "+1 (555)-678-9012",
    address: "654 Cedar Avenue, Colorado, Zip code: 80202",
    location: "K.K..nagar, Chennai",
    appointmentType: "Offline Appointment",
    diagnosed: ["Arthritis"],
    initials: "RI",
  },
};

export const vitals = [
  { label: "Weight", value: "70 kg", color: "bg-blue-100 text-blue-600" },
  { label: "Blood Pressure", value: "120/80 mm hg", color: "bg-orange-100 text-orange-600" },
  { label: "Body temperature", value: "97.2 F", color: "bg-amber-100 text-amber-600" },
  { label: "Oxygen saturation", value: "80%", color: "bg-green-100 text-green-600" },
  { label: "Heart rate", value: "105 bpm", color: "bg-red-100 text-red-600", highlight: true },
];

export const chatMessages = [
  { sender: "patient", name: "Kevin James (Patient)", time: "10:30 AM", text: "Hey, happy to hear from you. Yes, I will be back in a couple fo days.", emoji: null },
  { sender: "doctor", name: "Dr. Dristin Watson (Doctor)", time: "10:30 AM", text: "Great, I'm looking forward to meet you soon.. 😊", emoji: null },
  { sender: "patient", name: "Kevin James (Patient)", time: "10:30 AM", text: "Hey, happy to hear from you. Yes, I will be back in a couple fo days.", emoji: null },
  { sender: "patient", name: "Kevin James (Patient)", time: "10:30 AM", text: "Here are some Design i took earlier today.", emoji: "❤️" },
  { sender: "doctor", name: "Dr. Dristin Watson (Doctor)", time: "10:30 AM", text: "Great, I'm looking forward to meet you soon.. 😊", emoji: "🤗" },
  { sender: "patient", name: "Kevin James (Patient)", time: "10:30 AM", text: "Hey, happy to hear from you.", emoji: "👍" },
];

export const labReports = [
  { name: "kevin_ecg_test_reports_01/01/2025.pdf", lab: "PathLab Laboratory, Chennai, TN.", size: "7.5 MB", version: "3.22.22", time: "11:15 AM", updated: "Apr 25 | 9:25am", type: "pdf" },
  { name: "kevin_lab_blood_test_reports_01/01/2025.doc", lab: "PathLab Laboratory, Chennai, TN.", size: "7.5 MB", version: "3.22.22", time: "11:15 AM", updated: "Apr 25 | 9:25am", type: "doc" },
  { name: "kevin_ecg_test_reports_01/01/2025.pdf", lab: "PathLab Laboratory, Chennai, TN.", size: "7.5 MB", version: "3.22.22", time: "11:15 AM", updated: "Apr 25 | 9:25am", type: "pdf" },
  { name: "kevin_ecg_test_reports_01/01/2025.pdf", lab: "PathLab Laboratory, Chennai, TN.", size: "7.5 MB", version: "3.22.22", time: "11:15 AM", updated: "Apr 25 | 9:25am", type: "pdf" },
];
