import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";

// Manual spec for custom (non-auth) routes.
// As you build /api/doctors, /api/appointments, etc., add their paths here.
// Auth endpoints are auto-generated by Better Auth's openAPI plugin below.
const customSpec = {
  paths: {} as Record<string, unknown>,
  tags: [] as Array<{ name: string; description: string }>,
};

export async function GET() {
  // Auto-generated spec from Better Auth (stays in sync with your auth config)
  const authSpec = await auth.api.generateOpenAPISchema();

  // Merge both specs into one unified OpenAPI document
  const spec = {
    openapi: "3.1.0",
    info: {
      title: "Aushadham API",
      description:
        "API documentation for Aushadham — an Ayurvedic healthcare platform.\n\n" +
        "**Auth endpoints** are auto-generated from the Better Auth config.\n" +
        "**Custom endpoints** (doctors, appointments, etc.) are added manually as they are built.",
      version: "0.1.0",
    },
    servers: [
      {
        url: "http://localhost:3000",
        description: "Local development",
      },
      {
        url: "https://prod-varunmatta.vercel.app",
        description: "Production",
      },
    ],
    paths: {
      ...((authSpec as Record<string, unknown>)?.paths ?? {}),
      ...customSpec.paths,
    },
    components: {
      ...((authSpec as Record<string, unknown>)?.components ?? {}),
    },
    tags: [
      ...((authSpec as Record<string, unknown>)?.tags
        ? (
            (authSpec as Record<string, unknown>).tags as Array<{
              name: string;
            }>
          )
        : []),
      ...customSpec.tags,
    ],
  };

  return NextResponse.json(spec);
}
